refactor SettingsPage
danilt2000/LuckyDiamond pull request #6
Opened 2024-01-30 16:48 UTC by Madara0330E

made adjustments to the SettingsPage

2024-01-30 17:38 UTC, CkutlsGit commented on luckydiamond/src/components/AsidebarComponent.vue
A minor stylistic error is an unnecessary space on the 20th line. It's insignificant, but it's a good job.

2024-01-30 17:40 UTC, CkutlsGit commented on luckydiamond/src/pages/SettingsPage.vue
A minor stylistic error is that the section with the "settings" class is not exactly positioned, I would also add a space between the 19th and 20th lines. As it is, the job is done perfectly.

2024-01-30 17:42 UTC, CkutlsGit commented on luckydiamond/src/router/router.js
Perfect job, but I would add a space between the 6th and 7th line.

2024-01-30 17:43 UTC, CkutlsGit requested changes
Good job. My verdict: **5-**
@Madara0330E

2024-01-31 18:56 UTC, danilt2000 commented
Good

2024-01-31 18:56 UTC, merged